# Generated by Django 6.0.5 on 2026-05-18 00:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendeeMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("user_id_a", models.UUIDField()),
                ("user_id_b", models.UUIDField()),
                ("match_score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("match_signals", models.JSONField(default=dict)),
                ("is_introduced", models.BooleanField(default=False)),
                ("introduced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"intelligence"."attendee_match"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "user_id_a", "user_id_b"), name="unique_attendee_match"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConnectionPrivacy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("event_id", models.UUIDField()),
                ("opted_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"intelligence"."connection_privacy"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "event_id"), name="unique_connection_privacy"
                    )
                ],
            },
        ),
    ]
