# Generated by Django 6.0.5 on 2026-05-22 09:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_add_attendee_match_connection_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('latency_ms', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"intelligence"."health_ping"',
                'indexes': [models.Index(fields=['service_name', '-checked_at'], name='idx_health_ping_service'), models.Index(fields=['-checked_at'], name='idx_health_ping_time')],
            },
        ),
    ]
