# Generated by Django 6.0.5 on 2026-05-25 16:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_add_report_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('requested_by', models.UUIDField()),
                ('report_type', models.CharField(max_length=50)),
                ('filters', models.JSONField(default=dict)),
                ('format', models.CharField(max_length=10)),
                ('cron_expression', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"intelligence"."scheduled_report"',
                'indexes': [models.Index(fields=['event_id', 'is_active'], name='idx_scheduled_report_event'), models.Index(fields=['is_active', 'next_run_at'], name='idx_scheduled_report_due')],
            },
        ),
    ]
